package com.example.speedify.feature_bengkel.domain.entity

import androidx.annotation.DrawableRes
import com.example.speedify.R

data class BengkelEntity(
    val id: String,
    val nama: String,
    val phone: String,
    val alamat: String,
    val lokasi: String,
    val deskripsi: String,
    @DrawableRes val foto: Int,
    val jenis_bengkel: String,
    val spesialisasi_bengkel: String,
    val waktu: String,
    val kecamatan: String,
    val kota: String,
    val harga: Number,
    val is_open: Boolean,
    val rating: Number,
    val review: Int,
)

val dummyBengkel = listOf(
    BengkelEntity(
        "1",
        "Sriwijaya Mobil",
        "08123456789",
        "Jl. Sriwijaya No. 1",
        "3.2",
        "Bengkel motor terbaik di kota Palembang",
        R.drawable.example_img,
        "Bengkel Resmi",
        "Mobil",
        "30 mins",
        "Kalidoni",
        "Kota Palembang",
        50000,
        true,
        4.7,
        100
    ),
    BengkelEntity(
        "2",
        "Honda Union Motor",
        "08123456789",
        "Jl. Sriwijaya No. 1",
        "2.7",
        "Bengkel motor terbaik di kota Palembang",
        R.drawable.example_img,
        "Bengkel Resmi",
        "Motor",
        "30 mins",
        "Kalidoni",
        "Kota Palembang",
        50000,
        true,
        4.5,
        100
    ),
    BengkelEntity(
        "3",
        "MSC Mobil",
        "08123456789",
        "Jl. Sriwijaya No. 1",
        "1.2",
        "Bengkel motor terbaik di kota Palembang",
        R.drawable.example_img,
        "Bengkel Resmi",
        "Mobil",
        "30 mins",
        "Kalidoni",
        "Kota Palembang",
        50000,
        true,
        4.3,
        100
    ),
    BengkelEntity(
        "4",
        "Honda Maju Motor",
        "08123456789",
        "Jl. Sriwijaya No. 1",
        "3.2",
        "Bengkel motor terbaik di kota Palembang",
        R.drawable.example_img,
        "Bengkel Resmi",
        "Motor",
        "30 mins",
        "Kalidoni",
        "Kota Palembang",
        50000,
        true,
        4.7,
        100
    ),
    BengkelEntity(
        "5",
        "Astra Mobil",
        "08123456789",
        "Jl. Sriwijaya No. 1",
        "1.7",
        "Bengkel motor terbaik di kota Palembang",
        R.drawable.example_img,
        "Bengkel Resmi",
        "Mobil",
        "30 mins",
        "Kalidoni",
        "Kota Palembang",
        50000,
        true,
        4.7,
        100
    ),
    BengkelEntity(
        "6",
        "Ace Motor",
        "08123456789",
        "Jl. Sriwijaya No. 1",
        "3.2",
        "Bengkel motor terbaik di kota Palembang",
        R.drawable.example_img,
        "Bengkel Resmi",
        "Motor",
        "30 mins",
        "Kalidoni",
        "Kota Palembang",
        50000,
        true,
        4.7,
        100
    ),
    BengkelEntity(
        "7",
        "Bengkel Abadi Jaya",
        "08123456789",
        "Jl. Sriwijaya No. 1",
        "2.5",
        "Bengkel motor terbaik di kota Palembang",
        R.drawable.example_img,
        "Bengkel Resmi",
        "Mobil",
        "30 mins",
        "Kalidoni",
        "Kota Palembang",
        50000,
        true,
        4.6,
        100
    ),
    BengkelEntity(
        "8",
        "Kawasaki Motor",
        "08123456789",
        "Jl. Sriwijaya No. 1",
        "3.2",
        "Bengkel motor terbaik di kota Palembang",
        R.drawable.example_img,
        "Bengkel Resmi",
        "Motor",
        "30 mins",
        "Kalidoni",
        "Kota Palembang",
        50000,
        true,
        4.7,
        100
    ),
    BengkelEntity(
        "9",
        "Berkah Jaya",
        "08123456789",
        "Jl. Sriwijaya No. 1",
        "3.2",
        "Bengkel motor terbaik di kota Palembang",
        R.drawable.example_img,
        "Bengkel Resmi",
        "Mobil",
        "30 mins",
        "Kalidoni",
        "Kota Palembang",
        50000,
        true,
        4.7,
        100
    ),
    BengkelEntity(
        "10",
        "Andalan Motor",
        "08123456789",
        "Jl. Sriwijaya No. 1",
        "3.2",
        "Bengkel motor terbaik di kota Palembang",
        R.drawable.example_img,
        "Bengkel Resmi",
        "Motor",
        "30 mins",
        "Kalidoni",
        "Kota Palembang",
        50000,
        true,
        4.7,
        100
    ),
)
